# -*- coding: utf-8 -*-
"""BERTScore-Reranker-Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZ9Rbaw1RmenrcKOaGuvs7GrTRSEGwQ1
"""

import bert_score
from bert_score import score
from bert_score import BERTScorer
from bert_score import plot_example
scorer = BERTScorer(lang="en", model_type = 'microsoft/deberta-xlarge-mnli', rescale_with_baseline=True)

st = time.process_time()

for q in range(len(query_info)):
  query_info[q]["top_k"]["BertScore_F1"] = []
  for i in range(len(query_info[q]['top_k']['chunks'])):
    cands = []
    refs = []
    cands = query_info[q]['top_k']['chunks'][i]
    refs = [query_info[q]['query'] for j in range(len(query_info[q]['top_k']['chunks'][i]))]

    P, R, F1 = scorer.score(cands, refs)
    query_info[q]["top_k"]["BertScore_F1"].append(F1)

et = time.process_time()
res = et - st
print('\n\n****** CPU Execution time *******: ', res, 'seconds')

